server:
  port: 8761

spring:
  application:
    name: eureka-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tbook
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace